name = "KIMNeighborList"
uuid = "c95d6c40-0c10-4161-80ab-e9b71483fbc7"
version = "1.0.0"
authors = ["Amit Gupta <gupta839@umn.edu>"]
description = "Julia wrapper for KIM neighbor list implementation (C++ code by Mingjian Wen <wenxx151@gmail.com>)"
license = "MIT"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CxxWrap = "0.17"
julia = "1.10"
